"""
JavaScript/TypeScript stack generators (React, Next.js, Vue, Svelte, Node/Express)
"""

import json
from pathlib import Path
from typing import Dict

from src.stack_generators.base import BaseStackGenerator
from src.utils import write_file, process_template


class ReactTypeScriptGenerator(BaseStackGenerator):
    """Generator for React/TypeScript projects."""

    def generate_main_file(
        self,
        project_path: Path,
        variables: Dict[str, str]
    ) -> bool:
        """Generate React App.tsx and supporting files."""
        try:
            # App.tsx
            template_path = Path("templates/react_typescript_template.tsx")
            output_path = project_path / "src" / "App.tsx"
            process_template(template_path, output_path, variables)

            # index.tsx
            index_content = '''import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
'''
            write_file(project_path / "src" / "index.tsx", index_content)

            # index.html
            html_content = f'''<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{variables['project_name']}</title>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
'''
            write_file(project_path / "public" / "index.html", html_content)

            # CSS files
            write_file(project_path / "src" / "index.css", "body { margin: 0; }")
            write_file(project_path / "src" / "App.css", ".App { text-align: center; }")

            # tsconfig.json
            self._generate_tsconfig(project_path)

            return True
        except Exception as e:
            print(f"Error generating React files: {e}")
            return False

    def _generate_tsconfig(self, project_path: Path) -> bool:
        """Generate TypeScript configuration."""
        tsconfig = {
            "compilerOptions": {
                "target": "es5",
                "lib": ["dom", "dom.iterable", "esnext"],
                "allowJs": True,
                "skipLibCheck": True,
                "esModuleInterop": True,
                "allowSyntheticDefaultImports": True,
                "strict": True,
                "forceConsistentCasingInFileNames": True,
                "moduleResolution": "node",
                "resolveJsonModule": True,
                "isolatedModules": True,
                "noEmit": True,
                "jsx": "react-jsx"
            },
            "include": ["src"]
        }
        content = json.dumps(tsconfig, indent=2)
        return write_file(project_path / "tsconfig.json", content)

    def generate_dependencies(self, project_path: Path) -> bool:
        """Generate package.json for React."""
        project_name = project_path.name.lower().replace(' ', '-')

        package_json = {
            "name": project_name,
            "version": "0.1.0",
            "private": True,
            "dependencies": self.config.get('dependencies', {}),
            "devDependencies": self.config.get('dev_dependencies', {}),
            "scripts": {
                "start": "react-scripts start",
                "build": "react-scripts build",
                "test": "react-scripts test",
                "eject": "react-scripts eject"
            },
            "eslintConfig": {
                "extends": ["react-app", "react-app/jest"]
            },
            "browserslist": {
                "production": [">0.2%", "not dead", "not op_mini all"],
                "development": ["last 1 chrome version", "last 1 firefox version", "last 1 safari version"]
            }
        }

        content = json.dumps(package_json, indent=2)
        return write_file(project_path / "package.json", content)


class NextJSTypeScriptGenerator(BaseStackGenerator):
    """Generator for Next.js/TypeScript projects."""

    def generate_main_file(
        self,
        project_path: Path,
        variables: Dict[str, str]
    ) -> bool:
        """Generate Next.js page files."""
        try:
            # pages/index.tsx
            index_content = f'''import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {{
  return (
    <div className={{styles.container}}>
      <Head>
        <title>{variables['project_name']}</title>
        <meta name="description" content="Generated by ContextCraft" />
      </Head>

      <main className={{styles.main}}>
        <h1 className={{styles.title}}>
          Welcome to {variables['project_name']}!
        </h1>
        <p className={{styles.description}}>
          Your Next.js TypeScript application is ready.
        </p>
        <p>Created: {variables['date']}</p>
      </main>
    </div>
  )
}}
'''
            write_file(project_path / "pages" / "index.tsx", index_content)

            # styles/Home.module.css
            css_content = '''.container {
  padding: 0 2rem;
}

.main {
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.title {
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
  text-align: center;
}

.description {
  margin: 4rem 0;
  line-height: 1.5;
  font-size: 1.5rem;
  text-align: center;
}
'''
            write_file(project_path / "styles" / "Home.module.css", css_content)

            # tsconfig.json
            self._generate_tsconfig(project_path)

            return True
        except Exception as e:
            print(f"Error generating Next.js files: {e}")
            return False

    def _generate_tsconfig(self, project_path: Path) -> bool:
        """Generate TypeScript configuration for Next.js."""
        tsconfig = {
            "compilerOptions": {
                "target": "es5",
                "lib": ["dom", "dom.iterable", "esnext"],
                "allowJs": True,
                "skipLibCheck": True,
                "strict": True,
                "forceConsistentCasingInFileNames": True,
                "noEmit": True,
                "esModuleInterop": True,
                "module": "esnext",
                "moduleResolution": "bundler",
                "resolveJsonModule": True,
                "isolatedModules": True,
                "jsx": "preserve",
                "incremental": True,
                "plugins": [{"name": "next"}],
                "paths": {"@/*": ["./*"]}
            },
            "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
            "exclude": ["node_modules"]
        }
        content = json.dumps(tsconfig, indent=2)
        return write_file(project_path / "tsconfig.json", content)

    def generate_dependencies(self, project_path: Path) -> bool:
        """Generate package.json for Next.js."""
        project_name = project_path.name.lower().replace(' ', '-')

        package_json = {
            "name": project_name,
            "version": "0.1.0",
            "private": True,
            "scripts": {
                "dev": "next dev",
                "build": "next build",
                "start": "next start",
                "lint": "next lint"
            },
            "dependencies": self.config.get('dependencies', {}),
            "devDependencies": self.config.get('dev_dependencies', {})
        }

        content = json.dumps(package_json, indent=2)
        return write_file(project_path / "package.json", content)


class NodeExpressGenerator(BaseStackGenerator):
    """Generator for Node.js/Express projects."""

    def generate_main_file(
        self,
        project_path: Path,
        variables: Dict[str, str]
    ) -> bool:
        """Generate Express index.js."""
        template_path = Path("templates/node_express_template.js")
        output_path = project_path / "index.js"

        try:
            process_template(template_path, output_path, variables)
            return True
        except Exception as e:
            print(f"Error generating Express main file: {e}")
            return False

    def generate_dependencies(self, project_path: Path) -> bool:
        """Generate package.json for Express."""
        project_name = project_path.name.lower().replace(' ', '-')

        package_json = {
            "name": project_name,
            "version": "1.0.0",
            "description": "",
            "main": "index.js",
            "scripts": {
                "start": "node index.js",
                "dev": "nodemon index.js",
                "test": "jest"
            },
            "dependencies": self.config.get('dependencies', {}),
            "devDependencies": self.config.get('dev_dependencies', {})
        }

        content = json.dumps(package_json, indent=2)
        return write_file(project_path / "package.json", content)


# Factory function
def get_javascript_generator(stack_name: str, config: Dict) -> BaseStackGenerator:
    """
    Factory function to create the appropriate JavaScript stack generator.

    Args:
        stack_name: Name of the stack
        config: Stack configuration

    Returns:
        Appropriate generator instance
    """
    generators = {
        'react_typescript': ReactTypeScriptGenerator,
        'nextjs_typescript': NextJSTypeScriptGenerator,
        'node_express': NodeExpressGenerator,
        # Vue and Svelte can be added here
    }

    generator_class = generators.get(stack_name, NodeExpressGenerator)
    return generator_class(config)
